services:
  eureka-server:
    build:
      context: ./DiscoveryService
      dockerfile: Dockerfile
    container_name: discoveryserver_${RANDOM_SUFFIX}
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    container_name: userservice_${RANDOM_SUFFIX}
    ports:
      - "8091:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_${RANDOM_SUFFIX}:5432/usersdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      eureka.client.serviceUrl.defaultZone: http://discoveryserver_${RANDOM_SUFFIX}:8761/eureka
      SPRING_DOCKER_COMPOSE_ENABLED: "false"
      SPRING_RABBITMQ_HOST: rabbitmq_${RANDOM_SUFFIX}
    networks:
      - microservices-network
    depends_on:
      - postgres
      - rabbitmq

  ticketservice:
    build:
      context: ./TicketService
      dockerfile: Dockerfile
    container_name: ticketservice_${RANDOM_SUFFIX}
    ports:
      - "8093:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_${RANDOM_SUFFIX}:5432/ticketsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      eureka.client.serviceUrl.defaultZone: http://discoveryserver_${RANDOM_SUFFIX}:8761/eureka
      SPRING_DOCKER_COMPOSE_ENABLED: "false"
      SPRING_RABBITMQ_HOST: rabbitmq_${RANDOM_SUFFIX}
    networks:
      - microservices-network
    depends_on:
      - postgres
      - rabbitmq

  apigateway:
    build:
      context: ./Apigateway
      dockerfile: Dockerfile
    container_name: apigateway_${RANDOM_SUFFIX}
    ports:
      - "8090:8080"
    environment:
      SPRING_DOCKER_COMPOSE_ENABLED: "false"
      eureka.client.serviceUrl.defaultZone: http://discoveryserver_${RANDOM_SUFFIX}:8761/eureka
    networks:
      - microservices-network

  postgres:
    image: postgres:15.3-alpine3.18
    restart: always
    container_name: postgres_${RANDOM_SUFFIX}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - microservices-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_${RANDOM_SUFFIX}
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    healthcheck:
      test: ["CMD", "nc", "-z", "rabbitmq_${RANDOM_SUFFIX}", "5672"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
  rabbitmq_data:
  db-data: