services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongodb:
    image: "mongo"
    container_name: "mongodb"
    ports:
      - "27017:27017"

  userservice:
    build:
      context: ./UserService
    container_name: "userservice"
    ports:
      - "8091:8081"
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/userDB

  eventservice:
    build:
      context: ./EventService
    container_name: "eventservice"
    ports:
      - "8092:8082"
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/eventDB

  apigateway:
    build:
      context: ./Apigateway
    container_name: "apigateway"
    ports:
      - "8090:8080"
    depends_on:
      - rabbitmq
      - eventservice
      - userservice
    environment:
      - USER_SERVICE_HOST=userservice
      - USER_SERVICE_PORT=8081
      - EVENT_SERVICE_HOST=eventservice
      - EVENT_SERVICE_PORT=8082