#server:
#  port: 8083
#
#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://dev--yrfqzl5.us.auth0.com/
#          audience: https://eventusers,https://dev--yrfqzl5.us.auth0.com/userinfo
#  datasource:
#      url: jdbc:postgresql://localhost:5432/ticketsdb
#      username: postgres
#      password: postgres
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#  jpa:
#      hibernate:
#          ddl-auto: update
#      show-sql: true
#  application:
#      name: ticket-service
#  rabbitmq:
#      host: "localhost"
#      port: 5672
#      username: "guest"
#      password: "guest"
#  amqp:
#    deserialization:
#      trust:
#        all: true
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: false
#  instance:
#    prefer-ip-address: true
#  server:
#    enable-self-preservation: false
#
#rabbitmq:
#  exchange:
#    name: "rabbit_exchange"
#  queue:
#    name: "rabbit_subscription_queue"
#  routing:
#    key: "subscription_routing_key"
#
