#server:
#  port: 8080
#
#eureka:
#  client:
#    registerWithEureka: true
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#spring:
#  application:
#    name: api-gateway
#
#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://userservice
#          predicates:
#            - Path=/api/users/**
#        - id: event-service
#          uri: lb://eventservice
#          predicates:
#            - Path=/api/event/**
#        - id: ticket-service
#          uri: lb://ticketservice
#          predicates:
#            - Path=/api/tickets/**
#        - id: notificationservice
#          uri: lb://notificationservice
#          predicates:
#            - Path=/api/notification/**
#
